# Generated by Django 3.0.3 on 2020-02-13 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_tag', models.CharField(max_length=25, unique=True)),
                ('priority_color', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'verbose_name': 'Priority Tag',
                'verbose_name_plural': 'Priority Tags',
                'ordering': ['priority_tag'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('service_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='StatusCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_category_tag', models.CharField(max_length=45, unique=True)),
                ('status_category_color', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'verbose_name': 'Status Category',
                'verbose_name_plural': 'Status Categories',
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_service_name', models.CharField(max_length=100, unique=True, verbose_name='Sub-Service')),
                ('sub_service_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Sub-Service',
                'verbose_name_plural': 'Sub-Services',
                'ordering': ['sub_service_name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=10, unique=True)),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('action_description', models.TextField()),
                ('action_notes', models.TextField(blank=True, null=True)),
                ('notify_action', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Ticket notified')),
                ('category_status', models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='status.StatusCategory', verbose_name='Status')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='status.SubService', verbose_name='Sub-Service')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField()),
                ('action_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('service_history', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='status.Ticket')),
                ('service_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='status.StatusCategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubServiceServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='status.Priority')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Service')),
                ('subservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.SubService')),
            ],
            options={
                'verbose_name': 'Topology',
                'verbose_name_plural': 'Topology',
            },
        ),
        migrations.AddField(
            model_name='subservice',
            name='services',
            field=models.ManyToManyField(through='status.SubServiceServices', to='status.Service', verbose_name='Service'),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('subservices', models.ManyToManyField(to='status.SubService', verbose_name='Sub - Services')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
    ]
