# Generated by Django 2.0.5 on 2019-12-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceshistory',
            name='notify_action',
            field=models.BooleanField(),
        ),
    ]
