# Generated by Django 3.0.3 on 2020-02-22 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='services',
            field=models.ManyToManyField(to='status.Service', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='subserviceservices',
            name='subservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.SubService', verbose_name='Sub-Service'),
        ),
        migrations.AlterUniqueTogether(
            name='subserviceservices',
            unique_together={('service', 'subservice')},
        ),
    ]
