# Generated by Django 2.0.5 on 2020-01-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20200107_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceshistory',
            name='notify_action',
            field=models.BooleanField(choices=[(False, 'no'), (True, 'yes')], default=False, verbose_name='Ticket notified'),
        ),
    ]
