# Generated by Django 2.0.5 on 2020-01-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0008_servicehistorystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehistorystatus',
            name='action_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
