# Generated by Django 2.0.5 on 2020-01-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0010_auto_20200108_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceshistory',
            name='closing_notes',
        ),
    ]
