# Generated by Django 2.0.5 on 2020-01-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0012_auto_20200108_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceshistory',
            name='service_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='status.ServicesStatus'),
        ),
    ]
