# Generated by Django 2.0.5 on 2020-01-08 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0013_auto_20200108_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceshistory',
            name='business_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='status.BusinessService', verbose_name='Business Service'),
        ),
    ]
