# Generated by Django 3.0.7 on 2020-06-30 15:46

from django.db import migrations, models

import status.models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0045_auto_20200622_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default=status.models.getNewTicketId, max_length=10, unique=True),
        ),
    ]
